---
# Role tasks

- block:
    - name: setup groups
      group:
        gid: >-
          {{ item.gid | default(groups_defaults.gid) | default(omit) }}
        name : >-
          {{ item.name | default(groups_defaults.name) | default(omit) }}
        state: >-
          {{ item.state | default(groups_defaults.state) | default(omit) }}
        system : >-
          {{ item.system | default(groups_defaults.system) | default(omit) }}
      loop: "{{ groups_list }}"
      loop_control:
        label: "{{ item.name }}"
  tags:
    - role::groups
